### PR TITLE
Add shebang line to make app run on python3

### PR DESCRIPTION
**Pull request by admiral96**

### CODE REVIEW

**Comment by dashmug** [comment]
I don't think you need this. In your virtualenv, `python` should be python 3 anyway.

@mknecht @zkanda Thoughts?

**Comment by zkanda** [comment]
Yes I agree, for what reason your doing this @admiral96 ?

**Comment by admiral96** [comment]
Most python scripts have shebangs... and also just making sure they'd use python 3 on other computers

**Comment by mknecht** [comment]
@admiral96 when you're right, you gotta fight!  (and it rhymes, too!) :) even when @zkanda and @dashmug disagree :p 

you are right that scripts should have a shebang line so they can be easily run on UNIX. But only _scripts_, i.e. modules that are used by being run directly. Not regular Python modules that are used by being imported. Figure out which ones are scripts and then give _those_ proper shebang lines.

@dashmug is right that proper shebang lines should make _as few assumptions_ about the environment as possible. Basically, you're trying to say “run this as a python script” and let the environment figure out if that means the current virtualenv, a user-installed python or a system installation.

=> I expect a new PR that makes the shebang right in the scripts. :)

**Pull request closed without merging**
