### PR TITLE
Add MIT License

### PR DESCRIPTION
**Pull request by admiral96**

### CODE REVIEW

**Comment by admiral96** [comment]
@avnermiz 
Link: http://choosealicense.com/licenses/mit/#

**Comment by mknecht** [comment]
@admiral96 did you check with travis if they expect the license to be in a certain file or something?

**Comment by mknecht** [comment]
otherwise, if @avnermiz is fine, do merge

**Comment by admiral96** [comment]
@mknecht Nope. Only on github. It said that I should put it on a file called LICENSE.md

**Comment by mknecht** [comment]
alright, then let's wait for @avnermiz :)

**Comment by mknecht** [comment]
alright, then let's wait for @avnermiz :)

**Comment by avnermiz** [comment]
+1

**Pull request merged**
